version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: agenda
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db
      - redis

volumes:
  mysql_data: